inherit_from:
  - .rubocop_airbnb.yml

Metrics/LineLength:
  Enabled: false

AllCops:
  Exclude:
    - bin/*
    - db/schema.rb
    - db/**/*
    - db/migrate/*
    - config/**/*
    - config.ru
    - tmp/**/*
    - 'vendor/**/*'
    - Gemfile
    - Rakefile
    - channels/application_cable/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - app/helpers/*
    - app/models/pref.rb
    - app/models/user.rb

MixinUsage:
  Include:
    - app/**/*.rb