# version: 2.1
# jobs:
#   rspec:
#     working_directory: ~/campfs
#     docker:
#       - image: circleci/ruby
#     steps:
#       - checkout
#       - setup_remote_docker
#       - run:
#           name: Start containers and verify it is working
#           command: |
#             set -x
#             docker-compose up -d
#             docker exec campfs_web curl -4 --retry 10 --retry-delay 3 --retry-connrefused http://localhost:3000
#       - run:
#           name: Setup database
#           command: bundle exec rails db:migrate
#       - run:
#           name: Run rspec
#           command: docker-compose exec web rspec

#   rubocop:
#     working_directory: ~/campfs
#     docker:
#       - image: circleci/ruby
#     steps:
#       - checkout
#       - restore_cache:
#           keys:
#             - gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
#             - gemfiles-{{ .Branch }}-
#             - gemfiles-master-
#       - run:
#           name: bundle install
#           command: bundle check || bundle install --jobs=8 --clean
#       - run:
#           name: Run rubocop
#           command: bundle exec rubocop --parallel
#       - save_cache:
#           key: gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
#           paths:
#             - vendor/bundle

# orbs:
#   build-tools: circleci/build-tools@2.6
#   jq: circleci/jq@1.9.1
# workflows:
#   version: 2.1
#   build:
#     jobs:
#       - rspec
#       - rubocop


version: 2.1

orbs:
  ruby: circleci/ruby@1.1.0

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.7-node-browsers
        environment:
          BUNDLER_VERSION: 2.1.4
    steps:
      - checkout
      - ruby/install-deps

  test:
    parallelism: 3
    docker:
      - image: circleci/ruby:2.6.7-node-browsers
        environment:
          DB_HOST: 127.0.0.1
          RAILS_ENV: test
          BUNDLER_VERSION: 2.1.4
      - image: circleci/mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
          MYSQL_ROOT_HOST: '%'
    steps:
      - checkout
      - ruby/install-deps
      - run: mv config/database.yml.ci config/database.yml 
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      - ruby/rspec-test
      - ruby/rubocop-check

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build