name: Create a pull request for release.

on:
  pull_request:
    branches:
      - 'release/*'
    types:
      - 'closed'

jobs:
  create-release-pr:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Check if pr exists
        id: check_pr
        run: |
          pr_title=${{ github.base_ref }}
          base_branch='main'
          echo "::set-output name=count::$(gh pr list -S ${pr_title}' in:title' -B $base_branch | wc -l)"
          echo "::set-output name=pr_title::$pr_title"
          echo "::set-output name=base_branch::$base_branch"

      - name: Create release pr
        if: ${{ steps.check_pr.outputs.count == 0 }}
        run: |
          gh pr create -B main -t ${{ steps.check_pr.outputs.pr_title }}
